package lox

enum class TokenType {
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, ASTERISK, SLASH, SEMICOLON,

    BANG, BANG_EQUALS,
    EQUAL, EQUAL_EQUALS,
    GREATER_THAN, GREATER_THAN_EQUALS,
    LESSER_THAN, LESSER_THAN_EQUALS,

    IDENTIFIER, STRING, NUMBER,

    AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR,
    PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,

    EOF
}